### ISSUE TITLE
Strokes Gained Stats?

### ISSUE THREAD

**Issue by gheemony** [cgwhitehead/golfstats#1]
What stats does this scrape?
- round-by-round scores? It seems to.
- round-by-round conventional stats (GIR, Driving Distance)? It seems to.
- round-by-round strokes gained stats (SG: Total, SG:Off the Tee, etc)? Not certain.

Thank you.

**Comment by cgwhitehead** [comment]
Hey, I'm flattered you're looking at my stuff. No one's ever come here before.

In 2016 it scraped all of the scorecard stats from pga tour dot com, but I can't imagine it still works. Websites tend to update or make small changes that in turn break a lot of scrapers. The folk at fantasy football analytics have to update theirs every season for this reason. 

Also, some of the libraries aren't maintained and probably don't work with recent R versions. I can't even find a version of rlist to install in my new workspace to try and make this run. 

To be frank, this was a learning exercise from several years ago. I was proud of it and it demonstrates making web connections, etl of json to dataframes, and some data cleaning in R. At the same time it's not very elegant. 

If you're looking to scrape without too much code. I'd look at selenium. They have a browser tool I think. Also this looked useful if you want to do a little coding: [How to scrape golf stats](https://bigishdata.com/2016/03/05/gather-all-the-pga-tour-stats/) 

If you're learning R and you want to fork this and get it up and running again that'd be cool too. If you're looking to learn, but not set on R, then I'd point you at Python for a project like this. 

I'll update the readme to reflect this information. Closing this issue.

**Comment by gheemony** [comment]
Thanks for taking the time for a detailed reply. Even though not usable itself, your project helped me to think about how to build my own scraper. I am at the same stage you were at back then: learning R generally and learning to scrape HTML, parse JSON, build data tables, etc.  So thank you for making your project publicly available!

parag.gheewala@gmail.com | 425.503.3039 | LinkedIn
